export const ACTIONS = {
  SET_TABLE_DATA: "SET_TABLE_DATA",
  LOADING_TABLE: "LOADING_TABLE",
  SAVING: "SAVING",
  GET_TABLE_DATA: "GET_TABLE_DATA",
  SET_ROW_DATA: "SET_ROW_DATA",
  ADD_MODAL: "ADD_MODAL",
  EDIT_MODAL: "EDIT_MODAL",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE"
};

