export const ACTIONS = {
  SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
  LOADING: "LOADING",
  AUTO_REFRESH: "AUTO_REFRESH",
  SAVING: "SAVING",
  SET_BASE_ID: "SET_BASE_ID",
  SET_CLIENT_ID: "SET_CLIENT_ID",
  SET_BASE_NAME: "SET_BASE_NAME",
  SET_CLIENT_NAME: "SET_CLIENT_NAME",
  SET_BASE_DATA: "SET_BASE_DATA",
  SET_GANTT_DATA: "SET_GANTT_DATA",
  SET_ROW_DATA: "SET_ROW_DATA",
  SET_VIEW_MODE: "SET_VIEW_MODE",
  SET_VIEW_MODE_BASE: "SET_VIEW_MODE_BASE",
  SET_VIEW_MODE_CLIENT: "SET_VIEW_MODE_CLIENT",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE"
};
