export const ACTIONS = {
  SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
  SET_FILTERS: "SET_FILTERS",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  SET_ENUMERATORS: "SET_ENUMERATORS",
  SET_OPERATIONS_ENUMERATORS: "SET_OPERATIONS_ENUMERATORS",
  SET_MODAL_OPEN: "SET_MODAL_OPEN",
  SET_OPERATION_DATA: "SET_OPERATION_DATA",
  LOADING: "LOADING",
  SAVING: "SAVING",
  AUTO_REFRESH: "AUTO_REFRESH"
};
