export const ACTIONS = {
  GET_LIST_TABLE: "GET_LIST_TABLE",
  ROW_DATA_SET: "ROW_DATA_SET",
  MODAL_USER_ADD: "MODAL_USER_ADD",
  MODAL_USER_EDIT: "MODAL_USER_EDIT",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE"
};
