export const ACTIONS = {
  SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
  SET_FILTERS: "SET_DASHBOARD_DATA",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  SET_ENUMERATORS: "SET_ENUMERATORS",
  LOADING: "LOADING",
  AUTO_REFRESH: "AUTO_REFRESH"
};
