export const ACTIONS = {
  SET_TABLE_DATA_USER: "SET_TABLE_DATA_USER",
  LOADING_TABLE_USER: "LOADING_TABLE_USER",
  SAVING_USER: "SAVING_USER",
  SET_ENUMERATORS: "SET_ENUMERATORS",
  SET_FILTERS: "SET_FILTERS",
  SET_TABLE_DATA_USER_SKILLS: "SET_TABLE_DATA_USER_SKILLS",
  LOADING_TABLE_USER_SKILLS: "LOADING_TABLE_USER_SKILLS",
  SAVING_USER_SKILLS: "SAVING_USER_SAVING_USER_SKILLS",
  SET_ROW_DATA: "SET_ROW_DATA",
  ADD_MODAL_USER: "ADD_MODAL_USER",
  ADD_MODAL_USER_SKILLS: "ADD_MODAL_USER_SKILLS",
  EDIT_MODAL_USER: "EDIT_MODAL_USER",
  EDIT_MODAL_USER_SKILLS: "EDIT_MODAL_USER_SKILLS",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE"
};
