export const ACTIONS = {
  SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
  LOADING: "LOADING",
  SAVING: "SAVING",
  SET_ROW_DATA: "SET_ROW_DATA",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  SET_FILTERS: "SET_FILTERS",
  AUTO_REFRESH: "AUTO_REFRESH",
  SET_ENUMERATORS: "SET_ENUMERATORS",
};
